### ISSUE TITLE
Is there any live-cd where KWipe is included?

### ISSUE THREAD

**Issue by grufocom** [PyCoder/KWipe#2]
I would like to use KWipe with a live CD to boot via PXE.
Do I have to build one myself or do you know of one?

**Comment by PyCoder** [comment]
Hi

There is no live-cd for kwipe.
You can just use any live-cd (Ubuntu, Fedora, Slax, etc) you like and start KWipe on it. Installations
of any packages isn't necessary with the PyInstaller Package (only 64bit).

https://github.com/PyCoder/KWipe/releases/tag/3.0.3

Cheers

**Comment by grufocom** [comment]
Thank you, I downloaded gparted live system installed it into my pxe environment and integrated KWipe into that.
Works as expected! :-)
