### ISSUE TITLE
KWipe-3.1.2 not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by github4030** [PyCoder/KWipe#9]
Hello
I run the KWipe-3.0.3 source code on Ubuntu 22.04 without any problems but running the KWipe 3.1.2 source code shows the following error in the terminal:

/home/sky/Downloads/KWipe-3.1.2/share/kwipe/KWipe.py
Traceback (most recent call last):
File "/home/sky/Downloads/KWipe-3.1.2/share/kwipe/KWipe.py", line 23, in <module>
from main import KWipe
File "/home/sky/Downloads/KWipe-3.1.2/share/kwipe/main.py", line 35, in <module>
import directio
ModuleNotFoundError: No module named 'directio'

Running the KWipe-3.1.2-x86_64 file also shows the following error in the terminal:

Traceback (most recent call last):
File "KWipe.py", line 21, in <module>
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/_MEI0s3H9B/libstdc++.so.6)
[25381] Failed to execute script 'KWipe' due to unhandled exception!

Please help me to solve this problem. 
Thank you very much

**Comment by PyCoder** [comment]
Hi

Sorry for the late response.

Both errors have to do with your system and missing requirements

1. directio is not installed on your system ---> pip install directio 
2. Ubuntu 22.04 uses glibc-2.35 and the pyinstaller packages was made for glibc-2.36, so it's not compatible
